"""Build .ics calendar files for LSAT study sessions."""

from datetime import date, datetime, timedelta

from icalendar import Alarm, Calendar, Event, vDuration, vText


_DAY_NAME_TO_WEEKDAY = {
    "mon": 0, "tue": 1, "wed": 2, "thu": 3,
    "fri": 4, "sat": 5, "sun": 6,
}


def build_ics(
    exam_date_str: str | None,
    weak_areas: list[tuple[str, int]],
    days: list[str],
    start_time: str,
    duration_minutes: int,
) -> bytes:
    """Generate a .ics calendar file with one VEVENT per selected study day.

    Args:
        exam_date_str: ISO date string for the exam, or None (defaults 8 weeks out).
        weak_areas: Ranked list of (question_type, error_count) tuples.
        days: List of day abbreviations to schedule, e.g. ["mon", "wed", "fri"].
        start_time: "HH:MM" string for the event start time (local, no tz).
        duration_minutes: Length of each study session in minutes.

    Returns:
        Raw bytes of the .ics file.
    """
    today = date.today()

    if exam_date_str:
        try:
            exam = date.fromisoformat(exam_date_str)
        except ValueError:
            exam = today + timedelta(weeks=8)
    else:
        exam = today + timedelta(weeks=8)

    if exam <= today:
        exam = today + timedelta(weeks=8)

    # Parse start time.
    try:
        hour, minute = (int(p) for p in start_time.split(":"))
    except Exception:
        hour, minute = 19, 0

    target_weekdays = {_DAY_NAME_TO_WEEKDAY[d.lower()] for d in days if d.lower() in _DAY_NAME_TO_WEEKDAY}
    if not target_weekdays:
        target_weekdays = {0, 2, 4}  # Mon/Wed/Fri fallback

    top_areas = [qt for qt, _ in weak_areas[:3]] if weak_areas else ["Logical Reasoning"]

    cal = Calendar()
    cal.add("prodid", "-//Ratio LSAT Tutor//ratio.study//EN")
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("x-wr-calname", vText("LSAT Study Plan"))

    # Cycle through weak areas as session focus topics.
    focus_cycle = top_areas if top_areas else ["LSAT Practice"]
    session_index = 0
    current = today

    while current <= exam:
        if current.weekday() in target_weekdays:
            focus = focus_cycle[session_index % len(focus_cycle)]
            dt_start = datetime(current.year, current.month, current.day, hour, minute)
            dt_end = dt_start + timedelta(minutes=duration_minutes)

            event = Event()
            event.add("summary", f"LSAT Study Session: {focus}")
            event.add("dtstart", dt_start)
            event.add("dtend", dt_end)
            event.add("description", (
                f"Focus area: {focus}\n"
                f"Duration: {duration_minutes} minutes\n"
                f"Exam date: {exam.isoformat()}\n\n"
                "Generated by Ratio — ratio.study"
            ))

            alarm = Alarm()
            alarm.add("action", "DISPLAY")
            alarm.add("description", f"LSAT study in 30 minutes: {focus}")
            alarm.add("trigger", timedelta(minutes=-30))
            event.add_component(alarm)

            cal.add_component(event)
            session_index += 1

        current += timedelta(days=1)

    return cal.to_ical()
